// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"] || "postgresql://postgres:postgres@localhost:5432/dummy",
  },
});
